packages:
  - "apps/*"
allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react@1.35.0
