import { z } from "zod";

export const ilrInitialValues = {
  arrivalDate: "",
  benefitsMonths: 0,
  claimedBenefits: false,
  currentIncome: "",
  currentStatus: "",
  employmentType: "",
  englishLevel: "B2",
  entryMethod: "legal",
  hasChildren: false,
  hasCriminalRecord: false,
  hasDebts: false,
  hasOverstayed: false,
  hasPartner: false,
  hasVolunteering: false,
  illegalPenaltyYears: 20,
  incomeHistory: [] as unknown[],
  incomeYears: 3,
  isBNO: false,
  isBritishPartner: false,
  isGlobalTalent: false,
  isInnovatorFounder: false,
  isPublicService: false,
  isRefugee: false,
  numberOfChildren: 0,
  occupation: "",
  occupationLevel: "",
  overstayMonths: 0,
  overstayPenaltyYears: 20,
  partnerWorkStatus: "",
  passedLifeInUK: false,
  publicServiceYears: 0,
  refugeeType: "",
  visaCategory: "",
  visaStartDate: "",
  visitorPenaltyYears: 20,
  volunteeringHours: 0,
  volunteeringReductionYears: 3,
} as const;

export const getILRCalculatorSchema = () =>
  z.object({
    arrivalDate: z.string().default(ilrInitialValues.arrivalDate),
    benefitsMonths: z.number().default(ilrInitialValues.benefitsMonths),
    claimedBenefits: z.boolean().default(ilrInitialValues.claimedBenefits),
    currentIncome: z.string().default(ilrInitialValues.currentIncome),
    currentStatus: z.string().default(ilrInitialValues.currentStatus),
    employmentType: z.string().default(ilrInitialValues.employmentType),
    englishLevel: z.string().default(ilrInitialValues.englishLevel),
    entryMethod: z.string().default(ilrInitialValues.entryMethod),
    hasChildren: z.boolean().default(ilrInitialValues.hasChildren),
    hasCriminalRecord: z.boolean().default(ilrInitialValues.hasCriminalRecord),
    hasDebts: z.boolean().default(ilrInitialValues.hasDebts),
    hasOverstayed: z.boolean().default(ilrInitialValues.hasOverstayed),
    hasPartner: z.boolean().default(ilrInitialValues.hasPartner),
    hasVolunteering: z.boolean().default(ilrInitialValues.hasVolunteering),
    illegalPenaltyYears: z.number().default(ilrInitialValues.illegalPenaltyYears),
    incomeHistory: z.array(z.unknown()).default([...ilrInitialValues.incomeHistory]),
    incomeYears: z.number().default(ilrInitialValues.incomeYears),
    isBNO: z.boolean().default(ilrInitialValues.isBNO),
    isBritishPartner: z.boolean().default(ilrInitialValues.isBritishPartner),
    isGlobalTalent: z.boolean().default(ilrInitialValues.isGlobalTalent),
    isInnovatorFounder: z.boolean().default(ilrInitialValues.isInnovatorFounder),
    isPublicService: z.boolean().default(ilrInitialValues.isPublicService),
    isRefugee: z.boolean().default(ilrInitialValues.isRefugee),
    numberOfChildren: z.number().default(ilrInitialValues.numberOfChildren),
    occupation: z.string().default(ilrInitialValues.occupation),
    occupationLevel: z.string().default(ilrInitialValues.occupationLevel),
    overstayMonths: z.number().default(ilrInitialValues.overstayMonths),
    overstayPenaltyYears: z.number().default(ilrInitialValues.overstayPenaltyYears),
    partnerWorkStatus: z.string().default(ilrInitialValues.partnerWorkStatus),
    passedLifeInUK: z.boolean().default(ilrInitialValues.passedLifeInUK),
    publicServiceYears: z.number().default(ilrInitialValues.publicServiceYears),
    refugeeType: z.string().default(ilrInitialValues.refugeeType),
    visaCategory: z.string().default(ilrInitialValues.visaCategory),
    visaStartDate: z.string().default(ilrInitialValues.visaStartDate),
    visitorPenaltyYears: z.number().default(ilrInitialValues.visitorPenaltyYears),
    volunteeringHours: z.number().default(ilrInitialValues.volunteeringHours),
    volunteeringReductionYears: z.number().default(ilrInitialValues.volunteeringReductionYears),
  });
