-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE events
-- ADD CONSTRAINT events_status_fkey
-- FOREIGN KEY (status) REFERENCES event_status(value);
