-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."venue_schedule" add column "updated_at" time
--  not null default now();
