

name: CodeClimate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codeclimate:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Corepack for Yarn Berry
        run: corepack enable

      - name: Code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
            CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
            coverageCommand: yarn run coverage
            debug: true